# Site settings
title:          Dong Hyun's Blog
description:    " Java Developer 2018.04.01 ~ ing "
baseurl:        ""
url:            "https://xlr3zz.github.io"

# Author
author:
  name:         Dong Hyun
  url:          
  email:        xlr3zz@naver.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
